name: "Build Staging App"
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - develop
    types:
      - opened
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Needed in order to fetch Kalium sources for building
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_ENCODED }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/wiretest.jks
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build prod
        run: ./gradlew app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
#      - name: Build beta flavour
#        env:
#          GITHUB_USER: ${{ github.actor }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          ./gradlew assembleBetaDebug -p ./ --no-daemon
#          cp app/build/outputs/apk/beta/debug/com.wire.*.apk wire-android-${{inputs.flavour}}-pr-${{ github.event.pull_request.number }}.apk
#      - name: Build dev flavour
#        if: ${{ inputs.flavour == 'dev-debug' }}
#        env:
#          GITHUB_USER: ${{ github.actor }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          ./gradlew assembleDevDebug -p ./ --no-daemon
#          cp app/build/outputs/apk/dev/debug/com.wire.*.apk wire-android-${{inputs.flavour}}-pr-${{ github.event.pull_request.number }}.apk
#
