name: "Build Staging App"
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - develop
    types:
      - opened
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Needed in order to fetch Kalium sources for building
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_ENCODED }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/wiretest.jks
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build prod
        run:
          ./gradlew app:assembleBetaRelease -p ./ --no-daemon
        env:
          KEYSTORE_KEY_NAME_RELEASE: ${{ secrets.KEYSTORE_KEY_NAME_RELEASE }}
          KEYPWD_RELEASE: ${{ secrets.KEYPWD_RELEASE }}
          KEYSTOREPWD_RELEASE: ${{ secrets.KEYSTOREPWD_RELEASE }}
          ENABLE_SIGNING: ${{ secrets.ENABLE_SIGNING }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: app/build/outputs/